name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: -- Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.IMAGE_TAG }}
        
    - name: Push Image to ACR
      uses: julioarruda/pushimagetoregistry@v1
      with:
        acr-tokenname: ${{ secrets.REGISTRY_USERNAME }}
        acr-token: ${{ secrets.REGISTRY_PASSWORD }}
        acr-account: ${{ secrets.REGISTRY_NAME }}
        acr-imagename: ${{ secrets.IMAGE_TAG }}
    
    - name: -- Cosign Installer
      uses: sigstore/cosign-installer@v2.7.0
      
    - name: -- Write signing key to disk
      run: 'echo "$KEY" > cosing.key'
      shell: bash
      env:
        KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      
    - name: -- Sign the public docker image
      env:
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      run: cosign sign --key cosign.key ${{ secrets.IMAGE_TAG }}
